/* -------------------------------------------------
   글로벌 폴리필 – 반드시 다른 import 보다 먼저!
-------------------------------------------------- */
import '../lib/findDomNodePolyfill';   // or '@/lib/...'  (경로 alias 있으면)

import '@webex/widgets/dist/css/webex-widgets.css';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
